# Generated by Django 5.2.17 on 2026-08-24 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportmonks_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('short_code', models.CharField(blank=True, max_length=16)),
                ('logo_url', models.URLField(blank=True, max_length=512)),
                ('country_name', models.CharField(blank=True, max_length=255)),
                ('country_flag_url', models.URLField(blank=True, max_length=512)),
            ],
            options={
                'verbose_name': 'league',
                'verbose_name_plural': 'leagues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportmonks_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('short_code', models.CharField(blank=True, max_length=16)),
                ('crest_url', models.URLField(blank=True, max_length=512)),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportmonks_id', models.BigIntegerField(unique=True)),
                ('kickoff_at', models.DateTimeField()),
                ('synchronized_at', models.DateTimeField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixtures', to='fixtures.league')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_fixtures', to='fixtures.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_fixtures', to='fixtures.team')),
            ],
            options={
                'verbose_name': 'fixture',
                'verbose_name_plural': 'fixtures',
                'ordering': ['kickoff_at', 'id'],
                'indexes': [models.Index(fields=['kickoff_at'], name='fixture_kickoff_at_idx'), models.Index(fields=['league', 'kickoff_at'], name='fixture_league_kickoff_idx')],
            },
        ),
    ]
