# Generated by Django 5.2.17 on 2026-08-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='away_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='fixture',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('away_goals__isnull', True), ('home_goals__isnull', True)), models.Q(('away_goals__isnull', False), ('home_goals__isnull', False)), _connector='OR'), name='fixture_goals_pair_check'),
        ),
    ]
