# Generated by Django 5.2.17 on 2026-08-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_fixture_away_goals_fixture_home_goals_fixture_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='season_sportmonks_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['home_team', 'kickoff_at'], name='fixture_home_kickoff_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['away_team', 'kickoff_at'], name='fixture_away_kickoff_idx'),
        ),
    ]
