import { useEffect, useState } from "react";

const MOBILE_BREAKPOINT = 768;

/**
 * Reports whether the viewport is narrower than the mobile breakpoint.
 *
 * @remarks
 * Generated by the shadcn/ui CLI as a dependency of the sidebar primitive, but
 * adopted as project-authored source: it lands in `src/hooks/` rather than
 * `src/components/ui/`, so neither the Prettier exclusion nor the documentation
 * exemption for generated primitives covers it.
 *
 * It answers `false` on the server and on the first client render, because a
 * media query cannot be evaluated before a document exists. The real value
 * arrives in an effect, which is why the sidebar renders its desktop form first
 * and swaps to the mobile sheet once hydration has run.
 *
 * @returns `true` once the viewport is known to be narrower than 768 pixels.
 */
export function useIsMobile() {
  const [isMobile, setIsMobile] = useState<boolean | undefined>(undefined);

  useEffect(() => {
    const query = window.matchMedia(`(max-width: ${MOBILE_BREAKPOINT - 1}px)`);

    const readViewport = () => {
      setIsMobile(window.innerWidth < MOBILE_BREAKPOINT);
    };

    query.addEventListener("change", readViewport);
    readViewport();

    return () => query.removeEventListener("change", readViewport);
  }, []);

  return isMobile === true;
}
