# Generated by Django 5.2.17 on 2026-08-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authsession',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
