# Generated by Django 5.2.17 on 2026-08-25 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixtures', '0003_fixture_season_sportmonks_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTeamStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=8)),
                ('shots_total', models.PositiveSmallIntegerField()),
                ('shots_on_target', models.PositiveSmallIntegerField()),
                ('shots_inside_box', models.PositiveSmallIntegerField()),
                ('shots_blocked', models.PositiveSmallIntegerField()),
                ('big_chances_created', models.PositiveSmallIntegerField()),
                ('key_passes', models.PositiveSmallIntegerField()),
                ('corners', models.PositiveSmallIntegerField()),
                ('possession', models.PositiveSmallIntegerField()),
                ('passes', models.PositiveSmallIntegerField()),
                ('successful_passes', models.PositiveSmallIntegerField()),
                ('crosses', models.PositiveSmallIntegerField()),
                ('accurate_crosses', models.PositiveSmallIntegerField()),
                ('dribble_attempts', models.PositiveSmallIntegerField()),
                ('successful_dribbles', models.PositiveSmallIntegerField()),
                ('saves', models.PositiveSmallIntegerField()),
                ('tackles', models.PositiveSmallIntegerField()),
                ('interceptions', models.PositiveSmallIntegerField()),
                ('duels_won', models.PositiveSmallIntegerField()),
                ('fouls', models.PositiveSmallIntegerField()),
                ('yellow_cards', models.PositiveSmallIntegerField()),
                ('red_cards', models.PositiveSmallIntegerField()),
                ('offsides', models.PositiveSmallIntegerField()),
                ('synchronized_at', models.DateTimeField()),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_statistics', to='fixtures.fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_statistics', to='fixtures.team')),
            ],
            options={
                'verbose_name': 'match team statistic',
                'verbose_name_plural': 'match team statistics',
                'ordering': ['fixture', 'side'],
                'indexes': [models.Index(fields=['team', 'side'], name='match_statistic_team_side_idx')],
                'constraints': [models.UniqueConstraint(fields=('fixture', 'team'), name='match_statistic_team_unique'), models.UniqueConstraint(fields=('fixture', 'side'), name='match_statistic_side_unique'), models.CheckConstraint(condition=models.Q(('possession__lte', 100)), name='match_statistic_possession_range_check')],
            },
        ),
    ]
