# Generated by Django 5.2.17 on 2026-08-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchteamstatistic',
            name='dribble_attempts',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchteamstatistic',
            name='duels_won',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchteamstatistic',
            name='successful_dribbles',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchteamstatistic',
            name='tackles',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
